/*
 * Copyright (C) 2017 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

////////////////////////////////////////////////////////////////////////////////
// TODO: this should be autogenerated
////////////////////////////////////////////////////////////////////////////////

#include "greeter_service.pb.h"

#include "protorpc/src/test/greeter_service-gen.h"

#include "protorpc/basic_types.h"
#include "protorpc/service_descriptor.h"

#include <memory>

namespace protorpc_test {

using ::perfetto::protorpc::ServiceDescriptor;
Greeter::Service::~Service() = default;

ServiceDescriptor Greeter::Service::GetDescriptor() {
  ServiceDescriptor desc;
  desc.service_name = "Greeter";
  desc.service = this;

  // rpc SayHello(GreeterRequest) returns (GreeterReply) {}
  desc.methods.emplace_back(ServiceDescriptor::Method{
      /* method_name */ "SayHello",
      /* decoder */
      [](const std::string& proto_data) {
        std::unique_ptr<::protorpc_test::GreeterRequest> proto_obj(
            new ::protorpc_test::GreeterRequest());
        std::unique_ptr<::perfetto::protorpc::ProtoMessage> result;
        if (proto_obj->ParseFromString(proto_data))
          result.reset(proto_obj.release());
        return result;
      },
      /* new_reply_obj */
      []() {
        return std::unique_ptr<::perfetto::protorpc::ProtoMessage>(
            new ::protorpc_test::GreeterReply());
      },
      /* function */
      reinterpret_cast<ServiceDescriptor::Method::MethodPtr>(
          &Greeter::Service::SayHello)});

  // rpc SayGoodbye(GreeterRequest) returns (GreeterReply) {}
  desc.methods.emplace_back(ServiceDescriptor::Method{
      /* method_name */ "SayGoodbye",
      /* decoder */
      [](const std::string& proto_data) {
        std::unique_ptr<::protorpc_test::GreeterRequest> proto_obj(
            new ::protorpc_test::GreeterRequest());
        std::unique_ptr<::perfetto::protorpc::ProtoMessage> result;
        if (proto_obj->ParseFromString(proto_data))
          result.reset(proto_obj.release());
        return result;
      },
      /* new_reply_obj */
      []() {
        return std::unique_ptr<::perfetto::protorpc::ProtoMessage>(
            new ::protorpc_test::GreeterReply());
      },
      /* function */
      reinterpret_cast<ServiceDescriptor::Method::MethodPtr>(
          &Greeter::Service::SayGoodbye)});

  return desc;
}

}  // namespace protorpc_test
