/*
 * Copyright (C) 2017 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef PROTORPC_SRC_TEST_GREETER_SERVICE_H_
#define PROTORPC_SRC_TEST_GREETER_SERVICE_H_

#include "protorpc/service.h"

////////////////////////////////////////////////////////////////////////////////
// TODO: this should be autogenerated
////////////////////////////////////////////////////////////////////////////////
#include "protorpc/service_reply.h"
#include "protorpc/service_request.h"

#include "helloworld.pb.h"

namespace protorpc_test {

class Greeter {
 public:
  class Service {
   public:
    virtual ~Service() = default;

    using HelloRequest =
        ::perfetto::protorpc::ServiceRequest<::protorpc_test::HelloRequest>;
    using HelloReply = ::perfetto::protorpc::ServiceReply<::protorpc_test::HelloReply>;
    virtual void SayHello(HelloRequest, HelloReply) = 0;
  };

  class Client {
   public:
    virtual ~Client() = default;

    virtual void SayHello(HelloRequest, HelloReply) = 0;
  };
};

}  // namespace protorpc_test

////////////////////////////////////////////////////////////////////////////////

// Deliberately using a namespace != protorpc to spot subtle namespace dep bugs.
namespace protorpc_test {

class GreeterServiceImpl : public Greeter::Service {
 public:
  ~GreeterServiceImpl() override;
  void SayHello(HelloRequest, HelloReply) override;
};

}  // namespace protorpc_test

#endif  // PROTORPC_SRC_TEST_GREETER_SERVICE_H_
