/*
 * Copyright (C) 2017 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef PROTORPC_SRC_TEST_GREETER_SERVICE_GEN_H_
#define PROTORPC_SRC_TEST_GREETER_SERVICE_GEN_H_

////////////////////////////////////////////////////////////////////////////////
// TODO: this should be autogenerated
////////////////////////////////////////////////////////////////////////////////
#include "protorpc/deferred.h"
#include "protorpc/service.h"
#include "protorpc/service_descriptor.h"
#include "protorpc/service_proxy.h"

namespace protorpc_test {

// The request/response proto object in the .pb.h file.
class GreeterRequestMsg;
class GreeterReplyMsg;

using DeferredGreeterReply = ::perfetto::protorpc::Deferred<GreeterReplyMsg>;

class Greeter : public ::perfetto::protorpc::Service {
 public:
  static const ::perfetto::protorpc::ServiceDescriptor& GetDescriptor();

  virtual ~Greeter();
  virtual void SayHello(const GreeterRequestMsg&, DeferredGreeterReply) = 0;
  virtual void WaveGoodBye(const GreeterRequestMsg&, DeferredGreeterReply) = 0;
};

class GreeterProxy : public ::perfetto::protorpc::ServiceProxy {
 public:
  ~GreeterProxy() override;

  // ServiceProxy implementation.
  const ::perfetto::protorpc::ServiceDescriptor& GetDescriptor() override;

  // Greeter implementation.
  void SayHello(const GreeterRequestMsg&, DeferredGreeterReply);
  void WaveGoodBye(const GreeterRequestMsg&, DeferredGreeterReply);
};

}  // namespace protorpc_test

#endif  // PROTORPC_SRC_TEST_GREETER_SERVICE_GEN_H_
