/*
 * Copyright (C) 2017 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "tools/ftrace_proto_gen/proto_writer.h"

#include <stdio.h>

namespace perfetto {

void WriteProto(FILE* fout, const Proto& proto) {
  fprintf(fout, "// Autogenerated, do not edit.\n");
  fprintf(fout, "syntax = \"proto3\";\n");
  fprintf(fout, "message %s {\n", proto.name.c_str());
  for (const Proto::Field& field : proto.fields) {
    fprintf(fout, "  %s %s = %d;\n", field.type.c_str(), field.name.c_str(), field.number);
  }
  fprintf(fout, "}\n");
}

}  // namespace perfetto

