# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_swigdemo')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_swigdemo')
    _swigdemo = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_swigdemo', [dirname(__file__)])
        except ImportError:
            import _swigdemo
            return _swigdemo
        try:
            _mod = imp.load_module('_swigdemo', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _swigdemo = swig_import_helper()
    del swig_import_helper
else:
    import _swigdemo
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _swigdemo.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _swigdemo.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _swigdemo.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _swigdemo.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _swigdemo.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _swigdemo.SwigPyIterator_equal(self, x)

    def copy(self):
        return _swigdemo.SwigPyIterator_copy(self)

    def next(self):
        return _swigdemo.SwigPyIterator_next(self)

    def __next__(self):
        return _swigdemo.SwigPyIterator___next__(self)

    def previous(self):
        return _swigdemo.SwigPyIterator_previous(self)

    def advance(self, n):
        return _swigdemo.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _swigdemo.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _swigdemo.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _swigdemo.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _swigdemo.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _swigdemo.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _swigdemo.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _swigdemo.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class vectoreee(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectoreee, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectoreee, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _swigdemo.vectoreee_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _swigdemo.vectoreee___nonzero__(self)

    def __bool__(self):
        return _swigdemo.vectoreee___bool__(self)

    def __len__(self):
        return _swigdemo.vectoreee___len__(self)

    def __getslice__(self, i, j):
        return _swigdemo.vectoreee___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _swigdemo.vectoreee___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _swigdemo.vectoreee___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _swigdemo.vectoreee___delitem__(self, *args)

    def __getitem__(self, *args):
        return _swigdemo.vectoreee___getitem__(self, *args)

    def __setitem__(self, *args):
        return _swigdemo.vectoreee___setitem__(self, *args)

    def pop(self):
        return _swigdemo.vectoreee_pop(self)

    def append(self, x):
        return _swigdemo.vectoreee_append(self, x)

    def empty(self):
        return _swigdemo.vectoreee_empty(self)

    def size(self):
        return _swigdemo.vectoreee_size(self)

    def swap(self, v):
        return _swigdemo.vectoreee_swap(self, v)

    def begin(self):
        return _swigdemo.vectoreee_begin(self)

    def end(self):
        return _swigdemo.vectoreee_end(self)

    def rbegin(self):
        return _swigdemo.vectoreee_rbegin(self)

    def rend(self):
        return _swigdemo.vectoreee_rend(self)

    def clear(self):
        return _swigdemo.vectoreee_clear(self)

    def get_allocator(self):
        return _swigdemo.vectoreee_get_allocator(self)

    def pop_back(self):
        return _swigdemo.vectoreee_pop_back(self)

    def erase(self, *args):
        return _swigdemo.vectoreee_erase(self, *args)

    def __init__(self, *args):
        this = _swigdemo.new_vectoreee(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _swigdemo.vectoreee_push_back(self, x)

    def front(self):
        return _swigdemo.vectoreee_front(self)

    def back(self):
        return _swigdemo.vectoreee_back(self)

    def assign(self, n, x):
        return _swigdemo.vectoreee_assign(self, n, x)

    def resize(self, *args):
        return _swigdemo.vectoreee_resize(self, *args)

    def insert(self, *args):
        return _swigdemo.vectoreee_insert(self, *args)

    def reserve(self, n):
        return _swigdemo.vectoreee_reserve(self, n)

    def capacity(self):
        return _swigdemo.vectoreee_capacity(self)
    __swig_destroy__ = _swigdemo.delete_vectoreee
    __del__ = lambda self: None
vectoreee_swigregister = _swigdemo.vectoreee_swigregister
vectoreee_swigregister(vectoreee)

class FtraceEventField(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FtraceEventField, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FtraceEventField, name)
    __repr__ = _swig_repr
    __swig_setmethods__["type_and_name"] = _swigdemo.FtraceEventField_type_and_name_set
    __swig_getmethods__["type_and_name"] = _swigdemo.FtraceEventField_type_and_name_get
    if _newclass:
        type_and_name = _swig_property(_swigdemo.FtraceEventField_type_and_name_get, _swigdemo.FtraceEventField_type_and_name_set)
    __swig_setmethods__["offset"] = _swigdemo.FtraceEventField_offset_set
    __swig_getmethods__["offset"] = _swigdemo.FtraceEventField_offset_get
    if _newclass:
        offset = _swig_property(_swigdemo.FtraceEventField_offset_get, _swigdemo.FtraceEventField_offset_set)
    __swig_setmethods__["size"] = _swigdemo.FtraceEventField_size_set
    __swig_getmethods__["size"] = _swigdemo.FtraceEventField_size_get
    if _newclass:
        size = _swig_property(_swigdemo.FtraceEventField_size_get, _swigdemo.FtraceEventField_size_set)
    __swig_setmethods__["is_signed"] = _swigdemo.FtraceEventField_is_signed_set
    __swig_getmethods__["is_signed"] = _swigdemo.FtraceEventField_is_signed_get
    if _newclass:
        is_signed = _swig_property(_swigdemo.FtraceEventField_is_signed_get, _swigdemo.FtraceEventField_is_signed_set)

    def __eq__(self, other):
        return _swigdemo.FtraceEventField___eq__(self, other)

    def __init__(self):
        this = _swigdemo.new_FtraceEventField()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _swigdemo.delete_FtraceEventField
    __del__ = lambda self: None
FtraceEventField_swigregister = _swigdemo.FtraceEventField_swigregister
FtraceEventField_swigregister(FtraceEventField)

class FtraceEvent(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FtraceEvent, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FtraceEvent, name)
    __repr__ = _swig_repr
    __swig_setmethods__["name"] = _swigdemo.FtraceEvent_name_set
    __swig_getmethods__["name"] = _swigdemo.FtraceEvent_name_get
    if _newclass:
        name = _swig_property(_swigdemo.FtraceEvent_name_get, _swigdemo.FtraceEvent_name_set)
    __swig_setmethods__["id"] = _swigdemo.FtraceEvent_id_set
    __swig_getmethods__["id"] = _swigdemo.FtraceEvent_id_get
    if _newclass:
        id = _swig_property(_swigdemo.FtraceEvent_id_get, _swigdemo.FtraceEvent_id_set)
    __swig_setmethods__["fields"] = _swigdemo.FtraceEvent_fields_set
    __swig_getmethods__["fields"] = _swigdemo.FtraceEvent_fields_get
    if _newclass:
        fields = _swig_property(_swigdemo.FtraceEvent_fields_get, _swigdemo.FtraceEvent_fields_set)

    def __init__(self):
        this = _swigdemo.new_FtraceEvent()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _swigdemo.delete_FtraceEvent
    __del__ = lambda self: None
FtraceEvent_swigregister = _swigdemo.FtraceEvent_swigregister
FtraceEvent_swigregister(FtraceEvent)

class ProtoField(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ProtoField, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ProtoField, name)
    __repr__ = _swig_repr
    __swig_setmethods__["type"] = _swigdemo.ProtoField_type_set
    __swig_getmethods__["type"] = _swigdemo.ProtoField_type_get
    if _newclass:
        type = _swig_property(_swigdemo.ProtoField_type_get, _swigdemo.ProtoField_type_set)
    __swig_setmethods__["name"] = _swigdemo.ProtoField_name_set
    __swig_getmethods__["name"] = _swigdemo.ProtoField_name_get
    if _newclass:
        name = _swig_property(_swigdemo.ProtoField_name_get, _swigdemo.ProtoField_name_set)
    __swig_setmethods__["number"] = _swigdemo.ProtoField_number_set
    __swig_getmethods__["number"] = _swigdemo.ProtoField_number_get
    if _newclass:
        number = _swig_property(_swigdemo.ProtoField_number_get, _swigdemo.ProtoField_number_set)

    def __init__(self):
        this = _swigdemo.new_ProtoField()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _swigdemo.delete_ProtoField
    __del__ = lambda self: None
ProtoField_swigregister = _swigdemo.ProtoField_swigregister
ProtoField_swigregister(ProtoField)

class Proto(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Proto, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Proto, name)
    __repr__ = _swig_repr
    __swig_setmethods__["name"] = _swigdemo.Proto_name_set
    __swig_getmethods__["name"] = _swigdemo.Proto_name_get
    if _newclass:
        name = _swig_property(_swigdemo.Proto_name_get, _swigdemo.Proto_name_set)
    __swig_setmethods__["fields"] = _swigdemo.Proto_fields_set
    __swig_getmethods__["fields"] = _swigdemo.Proto_fields_get
    if _newclass:
        fields = _swig_property(_swigdemo.Proto_fields_get, _swigdemo.Proto_fields_set)

    def ToString(self):
        return _swigdemo.Proto_ToString(self)

    def __init__(self):
        this = _swigdemo.new_Proto()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _swigdemo.delete_Proto
    __del__ = lambda self: None
Proto_swigregister = _swigdemo.Proto_swigregister
Proto_swigregister(Proto)


def Test():
    return _swigdemo.Test()
Test = _swigdemo.Test

def GenerateProto(format, proto_out):
    return _swigdemo.GenerateProto(format, proto_out)
GenerateProto = _swigdemo.GenerateProto

def InferProtoType(field):
    return _swigdemo.InferProtoType(field)
InferProtoType = _swigdemo.InferProtoType

def GetNameFromTypeAndName(type_and_name):
    return _swigdemo.GetNameFromTypeAndName(type_and_name)
GetNameFromTypeAndName = _swigdemo.GetNameFromTypeAndName
# This file is compatible with both classic and new-style classes.


