/*
 * Copyright (C) 2017 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef TRACING_INCLUDE_TRACING_CORE_DATA_SOURCE_CONFIG_H_
#define TRACING_INCLUDE_TRACING_CORE_DATA_SOURCE_CONFIG_H_

#include <string>

namespace perfetto {

// TODO Like DataSourceDescriptor, also this should maybe be autogenerated from
// some data_source_config.proto that we'll have somewhere.
class DataSourceConfig {
 public:
  std::string data_source_name;  // e.g., "org.chromium.trace_events"

  // TODO: figure out how this should really look like.
  std::string trace_category_filters;  // e.g., "ipc,media,toplvel"
};

}  // namespace perfetto

#endif  // TRACING_INCLUDE_TRACING_CORE_DATA_SOURCE_CONFIG_H_
